version: '3.8'
services:
  backend:
    build:
      context: ./
      dockerfile: backend.Dockerfile
    ports:
      - "8080:5000"
    restart: unless-stopped

  frontend:
    build:
      context: ./
      dockerfile: frontend.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped