version: '3.8'
services:
  backend:
    image: linusnyren/ambulanceical:backend
    ports:
      - "8080:5000"
    restart: unless-stopped

  frontend:
    image: linusnyren/ambulanceical:frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped